version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: flat
      POSTGRES_USER: flat
      POSTGRES_DB: git
    volumes:
      - pgdata:/var/lib/postgresql/git-data
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
      target: api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    volumes:
      - ./api:/api
    depends_on:
      - postgres
    tty: true
    stdin_open: true
volumes:
  pgdata:
